language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_script:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-dist --no-progress --no-interaction
script:
  - vendor/bin/phpunit --stop-on-failure tests/